// multiple types

const LOAD_STATES_IDENTIFIERS = "LOAD_STATES_IDENTIFIERS";
const LOAD_STATE_DATA = "LOAD_STATE_DATA"
const LOAD_JURISDICTIONS = "LOAD_JURISDICTIONS";
const GET_STANDARDS = "GET_STANDARDS";
const SAVE_DAILY_PLANS = "SAVE_DAILY_PLANS";
const SAVE_WEEKLY_PLANS = "SAVE_WEEKLY_PLANS";
const CLEAR_DAILY_PLANS = "CLEAR_DAILY_PLANS";
const SAVE_CHOSEN_STATE = "SAVE_CHOSEN_STATE";
const SAVE_CONTENT_AREA_DATA = "SAVE_CONTENT_AREA_DATA";

export { LOAD_STATES_IDENTIFIERS, LOAD_STATE_DATA, LOAD_JURISDICTIONS, GET_STANDARDS, SAVE_DAILY_PLANS, SAVE_WEEKLY_PLANS, CLEAR_DAILY_PLANS, SAVE_CHOSEN_STATE, SAVE_CONTENT_AREA_DATA };