// multiple types

const LOAD_STATES_IDENTIFIERS = "LOAD_STATES_IDENTIFIERS";
const LOAD_STATE_DATA = "LOAD_STATE_DATA"
const LOAD_JURISDICTIONS = "LOAD_JURISDICTIONS";
const GET_STANDARDS = "GET_STANDARDS"

export { LOAD_STATES_IDENTIFIERS, LOAD_STATE_DATA, LOAD_JURISDICTIONS, GET_STANDARDS };